name: YT 3

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2,8,14 * * *'
jobs:
  youtube_bot:
    continue-on-error: true
    strategy:
      matrix:
        os: [macos-latest, windows-2019, windows-latest, windows-2019, windows-2022,windows-2022,windows-2022,windows-2022,windows-2022,windows-2022]
        

    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
           python-version: '3.10'

      - name: Install dependencies
        run: pip install selenium

      - name: Run Selenium script
        run: python my_selenium.py

      - name: Archive screenshots
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: screenshots-${{ matrix.os }}
          path: .
